### PR TITLE
Develop landing page

### PR DESCRIPTION
**Pull request by grantmontgomery**

### CODE REVIEW

**Comment by CSchmitz81** [comment]
I don't know that we're quite ready to merge the landing page into MVP yet.  We probably don't want to merge it until it's done, because we don't want the landing page being incomplete holding up the MVP.  At the current pace it may beat the MVP, but we can wait until it's done.

**Comment by grantmontgomery** [comment]
I haven’t tried to  merge anything yet. I think I’ve just put in a pull
request for certain sections.

Chris Schmitz <notifications@github.com> schrieb am Sa. 21. Sep. 2019 um
13:45:

**Comment by CSchmitz81** [comment]
I know, merges to branches like MVP can't be done without at least one approval of a PR.  I was just making sure it was clear that we're not going to do this merge until that point.  I'm not sure what you mean by "certain sections" because merges include everything from the commit being merged, unless you cherry pick changes into a new branch and merge that.

**Comment by CSchmitz81** [comment]
Closing to clean up PRs

**Pull request closed without merging**
